"""System category taxonomy seed data. No personal names or household data."""

TAXONOMY: dict[str, list[str]] = {
    "Income": [
        "Employment Income",
        "Business Income",
        "Freelance Income",
        "Marketplace Sales",
        "Government Refund",
        "Interest Income",
        "Investment Income",
        "Reimbursements",
        "Other Income",
    ],
    "Housing": [
        "Rent",
        "Mortgage",
        "Parking",
        "Storage or Locker",
        "Home Insurance",
        "Furniture",
        "Home Maintenance",
        "Household Supplies",
        "Property Tax",
        "Other Housing",
    ],
    "Utilities": [
        "Electricity",
        "Water",
        "Heating",
        "Internet",
        "Mobile Phone",
        "Home Phone",
        "Other Utilities",
    ],
    "Groceries": [
        "Groceries",
        "Specialty Food",
        "Household Consumables",
    ],
    "Dining Out": [
        "Restaurants",
        "Fast Food",
        "Cafes",
        "Food Delivery",
        "Takeout",
        "Bars and Nightlife",
    ],
    "Transportation": [
        "Fuel",
        "Public Transit",
        "Parking",
        "Tolls",
        "Rideshare and Taxi",
        "Vehicle Maintenance",
        "Vehicle Insurance",
        "Vehicle Payments",
        "Vehicle Registration",
        "Flights",
        "Other Transportation",
    ],
    "Healthcare": [
        "Doctor and Clinic",
        "Dental",
        "Pharmacy",
        "Vision",
        "Therapy",
        "Medical Devices",
        "Health Insurance",
        "Other Healthcare",
    ],
    "Personal Care": [
        "Gym and Fitness",
        "Hair",
        "Nails",
        "Beauty Services",
        "Skincare and Cosmetics",
        "Clothing",
        "Other Personal Care",
    ],
    "Entertainment": [
        "Streaming",
        "Movies and Events",
        "Music",
        "Television Services",
        "Hobbies",
        "Other Entertainment",
    ],
    "Games": [
        "Video Games",
        "Mobile Games",
        "Gaming Subscriptions",
        "Gaming Hardware",
        "In Game Purchases",
        "Board Games",
        "Other Games",
    ],
    "Software and Technology": [
        "AI Tools",
        "Programming Tools",
        "Cloud Storage",
        "Productivity Software",
        "Domain Names and Hosting",
        "Creative Software",
        "Electronics",
        "Computer Hardware",
        "Mobile Devices",
        "Other Technology",
    ],
    "Travel": [
        "Flights",
        "Hotels",
        "Vacation Rentals",
        "Travel Transportation",
        "Tours and Activities",
        "Travel Dining",
        "Travel Shopping",
        "Travel Insurance",
        "Other Travel",
    ],
    "Gifts and Donations": [
        "Gifts",
        "Charitable Donations",
        "Family Support",
        "Special Occasions",
    ],
    "Education": [
        "Books",
        "Courses",
        "Tuition",
        "Professional Development",
        "Other Education",
    ],
    "Business": [
        "Advertising",
        "Accounting",
        "Business Supplies",
        "Business Software",
        "Professional Services",
        "Business Travel",
        "Other Business",
    ],
    "Debt Payments": [
        "Student Loan Payment",
        "Vehicle Loan Payment",
        "Credit Card Payment",
        "Personal Loan Payment",
        "Mortgage Payment",
        "Interest Charges",
        "Other Debt Payment",
    ],
    "Financial and Government": [
        "Bank Fees",
        "Credit Card Fees",
        "Interest Charges",
        "Taxes",
        "Government Payments",
        "Accounting Fees",
        "Other Financial",
    ],
    "Investments and Savings": [
        "Registered Account Contribution",
        "Retirement Contribution",
        "Education Savings Contribution",
        "Non Registered Investment",
        "Cryptocurrency Purchase",
        "Savings Transfer",
        "Investment Withdrawal",
        "Other Investments",
    ],
    "Transfers": [
        "Account Transfer",
        "Credit Card Payment",
        "Shared Expense Settlement",
        "Investment Transfer",
        "Cash Transfer",
        "Unknown Transfer",
    ],
    "Refunds and Adjustments": [
        "Purchase Refund",
        "Charge Reversal",
        "Reimbursement",
        "Account Adjustment",
        "Cashback and Rewards",
    ],
    "Uncategorized": [],
}
