"""initial_schema

Revision ID: 89c8afdcbbf5
Revises: 
Create Date: 2026-08-01 20:15:03.910990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89c8afdcbbf5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_institutions',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('institution_type', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_institutions'))
    )
    op.create_table('households',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('default_currency', sa.String(length=3), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('assessment_confidence_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('analytics_default_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_households'))
    )
    op.create_table('user_accounts',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_accounts'))
    )
    op.create_index(op.f('ix_user_accounts_email'), 'user_accounts', ['email'], unique=True)
    op.create_table('assets',
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('owner_member_id', sa.UUID(), nullable=True),
    sa.Column('ownership_allocation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('institution_or_location', sa.String(length=200), nullable=True),
    sa.Column('asset_type', sa.String(length=64), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('current_value', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('include_in_net_worth', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_assets_household_id_households'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets'))
    )
    op.create_index(op.f('ix_assets_household_id'), 'assets', ['household_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('household_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('previous_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_audit_events_household_id_households'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], name=op.f('fk_audit_events_user_id_user_accounts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_household_id'), 'audit_events', ['household_id'], unique=False)
    op.create_index(op.f('ix_audit_events_timestamp'), 'audit_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_events_user_id'), 'audit_events', ['user_id'], unique=False)
    op.create_table('budgets',
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('subcategory_id', sa.UUID(), nullable=True),
    sa.Column('period_type', sa.String(length=32), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('household_member_id', sa.UUID(), nullable=True),
    sa.Column('ownership_allocation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_budgets_household_id_households'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budgets'))
    )
    op.create_index(op.f('ix_budgets_household_id'), 'budgets', ['household_id'], unique=False)
    op.create_table('categories',
    sa.Column('household_id', sa.UUID(), nullable=True),
    sa.Column('parent_category_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_level', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_system_seeded', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_categories_household_id_households'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_category_id'], ['categories.id'], name=op.f('fk_categories_parent_category_id_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories'))
    )
    op.create_index(op.f('ix_categories_household_id'), 'categories', ['household_id'], unique=False)
    op.create_index(op.f('ix_categories_parent_category_id'), 'categories', ['parent_category_id'], unique=False)
    op.create_table('categorization_rules',
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('match_type', sa.String(length=64), nullable=False),
    sa.Column('match_configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('subcategory_id', sa.UUID(), nullable=True),
    sa.Column('merchant_id', sa.UUID(), nullable=True),
    sa.Column('household_member_id', sa.UUID(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_human_confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_categorization_rules_household_id_households'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categorization_rules'))
    )
    op.create_index(op.f('ix_categorization_rules_household_id'), 'categorization_rules', ['household_id'], unique=False)
    op.create_table('category_proposals',
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('proposed_name', sa.String(length=200), nullable=False),
    sa.Column('proposed_parent_category_id', sa.UUID(), nullable=True),
    sa.Column('proposed_category_level', sa.Integer(), nullable=False),
    sa.Column('proposed_description', sa.Text(), nullable=True),
    sa.Column('reason_existing_insufficient', sa.Text(), nullable=True),
    sa.Column('example_event_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('affected_event_count', sa.Integer(), nullable=False),
    sa.Column('total_amount_affected', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('llm_provider', sa.String(length=64), nullable=True),
    sa.Column('llm_model', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_category_id', sa.UUID(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_category_proposals_household_id_households'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category_proposals'))
    )
    op.create_index(op.f('ix_category_proposals_household_id'), 'category_proposals', ['household_id'], unique=False)
    op.create_index(op.f('ix_category_proposals_status'), 'category_proposals', ['status'], unique=False)
    op.create_table('debts',
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('responsible_member_id', sa.UUID(), nullable=True),
    sa.Column('ownership_allocation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('lender', sa.String(length=200), nullable=True),
    sa.Column('original_principal', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('current_balance', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('minimum_payment', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('payment_frequency', sa.String(length=64), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('expected_payoff_date', sa.Date(), nullable=True),
    sa.Column('financial_account_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_debts_household_id_households'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_debts'))
    )
    op.create_index(op.f('ix_debts_household_id'), 'debts', ['household_id'], unique=False)
    op.create_table('external_participants',
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('source_system', sa.String(length=64), nullable=True),
    sa.Column('source_participant_id', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_external_participants_household_id_households'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_participants'))
    )
    op.create_index(op.f('ix_external_participants_household_id'), 'external_participants', ['household_id'], unique=False)
    op.create_table('household_members',
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('user_account_id', sa.UUID(), nullable=True),
    sa.Column('profile_role', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_household_members_household_id_households'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_account_id'], ['user_accounts.id'], name=op.f('fk_household_members_user_account_id_user_accounts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_household_members'))
    )
    op.create_index(op.f('ix_household_members_household_id'), 'household_members', ['household_id'], unique=False)
    op.create_index(op.f('ix_household_members_user_account_id'), 'household_members', ['user_account_id'], unique=False)
    op.create_table('import_profiles',
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=True),
    sa.Column('financial_account_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('structural_signature', sa.String(length=128), nullable=False),
    sa.Column('mapping_configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_import_profiles_household_id_households'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_profiles'))
    )
    op.create_index(op.f('ix_import_profiles_household_id'), 'import_profiles', ['household_id'], unique=False)
    op.create_index(op.f('ix_import_profiles_structural_signature'), 'import_profiles', ['structural_signature'], unique=False)
    op.create_table('planned_one_time_items',
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('responsible_member_id', sa.UUID(), nullable=True),
    sa.Column('ownership_allocation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('item_type', sa.String(length=64), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('subcategory_id', sa.UUID(), nullable=True),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('expected_month', sa.String(length=7), nullable=True),
    sa.Column('expected_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('actual_linked_event_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_planned_one_time_items_household_id_households'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_planned_one_time_items'))
    )
    op.create_index(op.f('ix_planned_one_time_items_household_id'), 'planned_one_time_items', ['household_id'], unique=False)
    op.create_table('recurring_cash_flow_items',
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('responsible_member_id', sa.UUID(), nullable=True),
    sa.Column('ownership_allocation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('transaction_type', sa.String(length=64), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('subcategory_id', sa.UUID(), nullable=True),
    sa.Column('expected_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('frequency', sa.String(length=64), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('next_expected_date', sa.Date(), nullable=True),
    sa.Column('annualized_amount', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('interest_rate', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('debt_remaining', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('linked_debt_id', sa.UUID(), nullable=True),
    sa.Column('linked_merchant_id', sa.UUID(), nullable=True),
    sa.Column('linked_account_id', sa.UUID(), nullable=True),
    sa.Column('is_variable_amount', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_recurring_cash_flow_items_household_id_households'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recurring_cash_flow_items'))
    )
    op.create_index(op.f('ix_recurring_cash_flow_items_household_id'), 'recurring_cash_flow_items', ['household_id'], unique=False)
    op.create_table('source_records',
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_scope', sa.String(length=200), nullable=True),
    sa.Column('native_source_id', sa.String(length=200), nullable=True),
    sa.Column('stable_source_key', sa.String(length=128), nullable=False),
    sa.Column('canonical_identity_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('content_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('first_seen_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('last_seen_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('first_imported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_imported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_revision_number', sa.Integer(), nullable=False),
    sa.Column('current_source_status', sa.String(length=64), nullable=False),
    sa.Column('latest_raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('deleted_at_source', sa.Boolean(), nullable=False),
    sa.Column('financial_account_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_source_records_household_id_households'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_records')),
    sa.UniqueConstraint('household_id', 'source_type', 'stable_source_key', name='uq_source_record_stable_key')
    )
    op.create_index(op.f('ix_source_records_canonical_identity_fingerprint'), 'source_records', ['canonical_identity_fingerprint'], unique=False)
    op.create_index(op.f('ix_source_records_content_fingerprint'), 'source_records', ['content_fingerprint'], unique=False)
    op.create_index(op.f('ix_source_records_current_source_status'), 'source_records', ['current_source_status'], unique=False)
    op.create_index(op.f('ix_source_records_financial_account_id'), 'source_records', ['financial_account_id'], unique=False)
    op.create_index(op.f('ix_source_records_household_id'), 'source_records', ['household_id'], unique=False)
    op.create_index(op.f('ix_source_records_native_source_id'), 'source_records', ['native_source_id'], unique=False)
    op.create_index(op.f('ix_source_records_source_type'), 'source_records', ['source_type'], unique=False)
    op.create_table('uploaded_files',
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=32), nullable=False),
    sa.Column('storage_key', sa.String(length=1000), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detected_source_type', sa.String(length=64), nullable=False),
    sa.Column('import_status', sa.String(length=64), nullable=False),
    sa.Column('malware_scan_status', sa.String(length=64), nullable=False),
    sa.Column('deletion_status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_uploaded_files_household_id_households'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user_accounts.id'], name=op.f('fk_uploaded_files_uploaded_by_user_accounts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uploaded_files'))
    )
    op.create_index(op.f('ix_uploaded_files_household_id'), 'uploaded_files', ['household_id'], unique=False)
    op.create_index(op.f('ix_uploaded_files_import_status'), 'uploaded_files', ['import_status'], unique=False)
    op.create_index(op.f('ix_uploaded_files_sha256_hash'), 'uploaded_files', ['sha256_hash'], unique=False)
    op.create_table('asset_snapshots',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_asset_snapshots_asset_id_assets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_snapshots'))
    )
    op.create_index(op.f('ix_asset_snapshots_asset_id'), 'asset_snapshots', ['asset_id'], unique=False)
    op.create_table('debt_snapshots',
    sa.Column('debt_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['debt_id'], ['debts.id'], name=op.f('fk_debt_snapshots_debt_id_debts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_debt_snapshots'))
    )
    op.create_index(op.f('ix_debt_snapshots_debt_id'), 'debt_snapshots', ['debt_id'], unique=False)
    op.create_table('financial_accounts',
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=True),
    sa.Column('account_name', sa.String(length=200), nullable=False),
    sa.Column('account_type', sa.String(length=64), nullable=False),
    sa.Column('account_subtype', sa.String(length=64), nullable=True),
    sa.Column('last_four_digits', sa.String(length=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('primary_owner_member_id', sa.UUID(), nullable=True),
    sa.Column('ownership_allocation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('current_reconciled_balance', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('include_in_net_worth', sa.Boolean(), nullable=False),
    sa.Column('include_in_cash_flow', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_financial_accounts_household_id_households'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institution_id'], ['financial_institutions.id'], name=op.f('fk_financial_accounts_institution_id_financial_institutions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['primary_owner_member_id'], ['household_members.id'], name=op.f('fk_financial_accounts_primary_owner_member_id_household_members'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_accounts'))
    )
    op.create_index(op.f('ix_financial_accounts_household_id'), 'financial_accounts', ['household_id'], unique=False)
    op.create_table('household_memberships',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('household_member_id', sa.UUID(), nullable=False),
    sa.Column('permission_role', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_household_memberships_household_id_households'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['household_member_id'], ['household_members.id'], name=op.f('fk_household_memberships_household_member_id_household_members'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], name=op.f('fk_household_memberships_user_id_user_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_household_memberships')),
    sa.UniqueConstraint('user_id', 'household_id', name='uq_membership_user_hh')
    )
    op.create_index(op.f('ix_household_memberships_household_id'), 'household_memberships', ['household_id'], unique=False)
    op.create_index(op.f('ix_household_memberships_household_member_id'), 'household_memberships', ['household_member_id'], unique=False)
    op.create_index(op.f('ix_household_memberships_user_id'), 'household_memberships', ['user_id'], unique=False)
    op.create_table('merchants',
    sa.Column('household_id', sa.UUID(), nullable=True),
    sa.Column('canonical_name', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('default_category_id', sa.UUID(), nullable=True),
    sa.Column('default_subcategory_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['default_category_id'], ['categories.id'], name=op.f('fk_merchants_default_category_id_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['default_subcategory_id'], ['categories.id'], name=op.f('fk_merchants_default_subcategory_id_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_merchants_household_id_households'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_merchants'))
    )
    op.create_index(op.f('ix_merchants_canonical_name'), 'merchants', ['canonical_name'], unique=False)
    op.create_index(op.f('ix_merchants_household_id'), 'merchants', ['household_id'], unique=False)
    op.create_table('source_record_versions',
    sa.Column('source_record_id', sa.UUID(), nullable=False),
    sa.Column('import_snapshot_id', sa.UUID(), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('content_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('field_differences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], name=op.f('fk_source_record_versions_source_record_id_source_records'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_record_versions'))
    )
    op.create_index(op.f('ix_source_record_versions_import_snapshot_id'), 'source_record_versions', ['import_snapshot_id'], unique=False)
    op.create_index(op.f('ix_source_record_versions_source_record_id'), 'source_record_versions', ['source_record_id'], unique=False)
    op.create_table('splitwise_expenses',
    sa.Column('source_record_id', sa.UUID(), nullable=False),
    sa.Column('native_splitwise_expense_id', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('expense_date', sa.Date(), nullable=True),
    sa.Column('total_estimated_amount', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('group_name', sa.String(length=200), nullable=True),
    sa.Column('splitwise_category', sa.String(length=200), nullable=True),
    sa.Column('paid_by_participant', sa.String(length=200), nullable=True),
    sa.Column('created_by_participant', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], name=op.f('fk_splitwise_expenses_source_record_id_source_records'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_splitwise_expenses'))
    )
    op.create_index(op.f('ix_splitwise_expenses_expense_date'), 'splitwise_expenses', ['expense_date'], unique=False)
    op.create_index(op.f('ix_splitwise_expenses_native_splitwise_expense_id'), 'splitwise_expenses', ['native_splitwise_expense_id'], unique=False)
    op.create_index(op.f('ix_splitwise_expenses_source_record_id'), 'splitwise_expenses', ['source_record_id'], unique=False)
    op.create_table('canonical_financial_events',
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('posted_date', sa.Date(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('confirmed_merchant_id', sa.UUID(), nullable=True),
    sa.Column('confirmed_description', sa.String(length=500), nullable=True),
    sa.Column('original_description', sa.String(length=1000), nullable=True),
    sa.Column('confirmed_amount', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('confirmed_currency', sa.String(length=3), nullable=True),
    sa.Column('original_currency', sa.String(length=3), nullable=True),
    sa.Column('original_amount', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('exchange_rate', sa.Numeric(precision=19, scale=8), nullable=True),
    sa.Column('confirmed_category_id', sa.UUID(), nullable=True),
    sa.Column('confirmed_subcategory_id', sa.UUID(), nullable=True),
    sa.Column('household_economic_share', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('transaction_direction', sa.String(length=16), nullable=True),
    sa.Column('recurring_status', sa.Boolean(), nullable=True),
    sa.Column('fixed_or_variable_status', sa.String(length=32), nullable=True),
    sa.Column('essential_or_discretionary_status', sa.String(length=32), nullable=True),
    sa.Column('one_time_status', sa.Boolean(), nullable=True),
    sa.Column('transfer_status', sa.String(length=32), nullable=False),
    sa.Column('refund_status', sa.String(length=32), nullable=False),
    sa.Column('reimbursement_status', sa.String(length=32), nullable=False),
    sa.Column('duplicate_status', sa.String(length=32), nullable=False),
    sa.Column('splitwise_match_status', sa.String(length=32), nullable=False),
    sa.Column('analytics_inclusion_status', sa.String(length=32), nullable=False),
    sa.Column('overall_assessment_status', sa.String(length=64), nullable=False),
    sa.Column('financial_account_id', sa.UUID(), nullable=True),
    sa.Column('ownership_allocation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('llm_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('user_notes', sa.Text(), nullable=True),
    sa.Column('is_category_user_confirmed', sa.Boolean(), nullable=False),
    sa.Column('is_allocation_user_confirmed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_category_id'], ['categories.id'], name=op.f('fk_canonical_financial_events_confirmed_category_id_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['confirmed_subcategory_id'], ['categories.id'], name=op.f('fk_canonical_financial_events_confirmed_subcategory_id_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['financial_account_id'], ['financial_accounts.id'], name=op.f('fk_canonical_financial_events_financial_account_id_financial_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_canonical_financial_events_household_id_households'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_canonical_financial_events'))
    )
    op.create_index(op.f('ix_canonical_financial_events_analytics_inclusion_status'), 'canonical_financial_events', ['analytics_inclusion_status'], unique=False)
    op.create_index(op.f('ix_canonical_financial_events_confirmed_category_id'), 'canonical_financial_events', ['confirmed_category_id'], unique=False)
    op.create_index(op.f('ix_canonical_financial_events_confirmed_subcategory_id'), 'canonical_financial_events', ['confirmed_subcategory_id'], unique=False)
    op.create_index(op.f('ix_canonical_financial_events_event_date'), 'canonical_financial_events', ['event_date'], unique=False)
    op.create_index(op.f('ix_canonical_financial_events_event_type'), 'canonical_financial_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_canonical_financial_events_financial_account_id'), 'canonical_financial_events', ['financial_account_id'], unique=False)
    op.create_index(op.f('ix_canonical_financial_events_household_id'), 'canonical_financial_events', ['household_id'], unique=False)
    op.create_index(op.f('ix_canonical_financial_events_overall_assessment_status'), 'canonical_financial_events', ['overall_assessment_status'], unique=False)
    op.create_table('import_snapshots',
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_file_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_scope', sa.String(length=200), nullable=True),
    sa.Column('financial_account_id', sa.UUID(), nullable=True),
    sa.Column('splitwise_group', sa.String(length=200), nullable=True),
    sa.Column('export_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('earliest_source_date', sa.Date(), nullable=True),
    sa.Column('latest_source_date', sa.Date(), nullable=True),
    sa.Column('source_row_count', sa.Integer(), nullable=False),
    sa.Column('new_record_count', sa.Integer(), nullable=False),
    sa.Column('unchanged_record_count', sa.Integer(), nullable=False),
    sa.Column('updated_record_count', sa.Integer(), nullable=False),
    sa.Column('possible_duplicate_count', sa.Integer(), nullable=False),
    sa.Column('conflict_count', sa.Integer(), nullable=False),
    sa.Column('missing_record_count', sa.Integer(), nullable=False),
    sa.Column('failed_row_count', sa.Integer(), nullable=False),
    sa.Column('import_status', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['financial_account_id'], ['financial_accounts.id'], name=op.f('fk_import_snapshots_financial_account_id_financial_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_import_snapshots_household_id_households'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_file_id'], ['uploaded_files.id'], name=op.f('fk_import_snapshots_uploaded_file_id_uploaded_files'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_snapshots'))
    )
    op.create_index(op.f('ix_import_snapshots_household_id'), 'import_snapshots', ['household_id'], unique=False)
    op.create_index(op.f('ix_import_snapshots_import_status'), 'import_snapshots', ['import_status'], unique=False)
    op.create_index(op.f('ix_import_snapshots_uploaded_file_id'), 'import_snapshots', ['uploaded_file_id'], unique=False)
    op.create_table('merchant_aliases',
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('alias', sa.String(length=300), nullable=False),
    sa.Column('normalized_alias', sa.String(length=300), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('fk_merchant_aliases_merchant_id_merchants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_merchant_aliases'))
    )
    op.create_index(op.f('ix_merchant_aliases_merchant_id'), 'merchant_aliases', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_merchant_aliases_normalized_alias'), 'merchant_aliases', ['normalized_alias'], unique=False)
    op.create_table('splitwise_participant_allocations',
    sa.Column('splitwise_expense_id', sa.UUID(), nullable=False),
    sa.Column('household_member_id', sa.UUID(), nullable=True),
    sa.Column('external_participant_id', sa.UUID(), nullable=True),
    sa.Column('amount_paid', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('amount_owed', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('net_share', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('source_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['splitwise_expense_id'], ['splitwise_expenses.id'], name=op.f('fk_splitwise_participant_allocations_splitwise_expense_id_splitwise_expenses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_splitwise_participant_allocations'))
    )
    op.create_index(op.f('ix_splitwise_participant_allocations_splitwise_expense_id'), 'splitwise_participant_allocations', ['splitwise_expense_id'], unique=False)
    op.create_table('categorization_assessments',
    sa.Column('canonical_financial_event_id', sa.UUID(), nullable=False),
    sa.Column('source_record_id', sa.UUID(), nullable=True),
    sa.Column('suggested_transaction_type', sa.String(length=64), nullable=True),
    sa.Column('suggested_merchant', sa.String(length=300), nullable=True),
    sa.Column('suggested_category_id', sa.UUID(), nullable=True),
    sa.Column('suggested_subcategory_id', sa.UUID(), nullable=True),
    sa.Column('suggested_ownership_allocation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('suggested_recurring_status', sa.Boolean(), nullable=True),
    sa.Column('suggested_fixed_or_variable', sa.String(length=32), nullable=True),
    sa.Column('suggested_essential_or_discretionary', sa.String(length=32), nullable=True),
    sa.Column('transfer_likelihood', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('refund_likelihood', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('category_fit', sa.String(length=64), nullable=True),
    sa.Column('decision_method', sa.String(length=64), nullable=True),
    sa.Column('llm_provider', sa.String(length=64), nullable=True),
    sa.Column('llm_model', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('structured_model_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('needs_human_review', sa.Boolean(), nullable=False),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_override_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['canonical_financial_event_id'], ['canonical_financial_events.id'], name=op.f('fk_categorization_assessments_canonical_financial_event_id_canonical_financial_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], name=op.f('fk_categorization_assessments_source_record_id_source_records'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categorization_assessments'))
    )
    op.create_index(op.f('ix_categorization_assessments_canonical_financial_event_id'), 'categorization_assessments', ['canonical_financial_event_id'], unique=False)
    op.create_table('financial_event_allocations',
    sa.Column('canonical_financial_event_id', sa.UUID(), nullable=False),
    sa.Column('household_member_id', sa.UUID(), nullable=True),
    sa.Column('external_participant_id', sa.UUID(), nullable=True),
    sa.Column('allocation_type', sa.String(length=64), nullable=False),
    sa.Column('allocation_percentage', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('allocation_amount', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('paid_amount', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('owed_amount', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['canonical_financial_event_id'], ['canonical_financial_events.id'], name=op.f('fk_financial_event_allocations_canonical_financial_event_id_canonical_financial_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['household_member_id'], ['household_members.id'], name=op.f('fk_financial_event_allocations_household_member_id_household_members'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_event_allocations'))
    )
    op.create_index(op.f('ix_financial_event_allocations_canonical_financial_event_id'), 'financial_event_allocations', ['canonical_financial_event_id'], unique=False)
    op.create_table('import_interpretations',
    sa.Column('import_snapshot_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('selected_worksheet', sa.String(length=200), nullable=True),
    sa.Column('selected_table_range', sa.String(length=100), nullable=True),
    sa.Column('header_row', sa.Integer(), nullable=True),
    sa.Column('data_start_row', sa.Integer(), nullable=True),
    sa.Column('data_end_row', sa.Integer(), nullable=True),
    sa.Column('ignored_rows', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('column_mappings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('date_format', sa.String(length=64), nullable=True),
    sa.Column('amount_convention', sa.String(length=64), nullable=True),
    sa.Column('default_currency', sa.String(length=3), nullable=True),
    sa.Column('description_template', sa.String(length=500), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sample_normalized_rows', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('structural_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_human_confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmed_by', sa.UUID(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('llm_provider', sa.String(length=64), nullable=True),
    sa.Column('llm_model', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['import_snapshot_id'], ['import_snapshots.id'], name=op.f('fk_import_interpretations_import_snapshot_id_import_snapshots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_interpretations'))
    )
    op.create_index(op.f('ix_import_interpretations_import_snapshot_id'), 'import_interpretations', ['import_snapshot_id'], unique=False)
    op.create_table('import_jobs',
    sa.Column('import_snapshot_id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('current_stage', sa.String(length=100), nullable=True),
    sa.Column('progress_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('source_row_count', sa.Integer(), nullable=False),
    sa.Column('processed_row_count', sa.Integer(), nullable=False),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('warning_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['import_snapshot_id'], ['import_snapshots.id'], name=op.f('fk_import_jobs_import_snapshot_id_import_snapshots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_jobs'))
    )
    op.create_index(op.f('ix_import_jobs_idempotency_key'), 'import_jobs', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_import_jobs_import_snapshot_id'), 'import_jobs', ['import_snapshot_id'], unique=False)
    op.create_index(op.f('ix_import_jobs_status'), 'import_jobs', ['status'], unique=False)
    op.create_table('raw_source_rows',
    sa.Column('import_snapshot_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_file_id', sa.UUID(), nullable=False),
    sa.Column('worksheet_name', sa.String(length=200), nullable=True),
    sa.Column('table_identifier', sa.String(length=100), nullable=True),
    sa.Column('source_row_number', sa.Integer(), nullable=False),
    sa.Column('original_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('row_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('parsing_status', sa.String(length=64), nullable=False),
    sa.Column('parsing_error', sa.Text(), nullable=True),
    sa.Column('classification', sa.String(length=64), nullable=True),
    sa.Column('source_record_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['import_snapshot_id'], ['import_snapshots.id'], name=op.f('fk_raw_source_rows_import_snapshot_id_import_snapshots'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], name=op.f('fk_raw_source_rows_source_record_id_source_records'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_file_id'], ['uploaded_files.id'], name=op.f('fk_raw_source_rows_uploaded_file_id_uploaded_files'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_source_rows')),
    sa.UniqueConstraint('import_snapshot_id', 'worksheet_name', 'source_row_number', name='uq_raw_row_snapshot_sheet_num')
    )
    op.create_index(op.f('ix_raw_source_rows_import_snapshot_id'), 'raw_source_rows', ['import_snapshot_id'], unique=False)
    op.create_index(op.f('ix_raw_source_rows_row_fingerprint'), 'raw_source_rows', ['row_fingerprint'], unique=False)
    op.create_index(op.f('ix_raw_source_rows_source_record_id'), 'raw_source_rows', ['source_record_id'], unique=False)
    op.create_table('source_event_relationships',
    sa.Column('source_record_id', sa.UUID(), nullable=False),
    sa.Column('canonical_financial_event_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=64), nullable=False),
    sa.Column('allocated_amount', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('match_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('match_method', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confirmed_by', sa.UUID(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['canonical_financial_event_id'], ['canonical_financial_events.id'], name=op.f('fk_source_event_relationships_canonical_financial_event_id_canonical_financial_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], name=op.f('fk_source_event_relationships_source_record_id_source_records'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_event_relationships'))
    )
    op.create_index(op.f('ix_source_event_relationships_canonical_financial_event_id'), 'source_event_relationships', ['canonical_financial_event_id'], unique=False)
    op.create_index(op.f('ix_source_event_relationships_source_record_id'), 'source_event_relationships', ['source_record_id'], unique=False)
    op.create_table('splitwise_overlap_assessments',
    sa.Column('splitwise_expense_id', sa.UUID(), nullable=False),
    sa.Column('candidate_financial_event_id', sa.UUID(), nullable=True),
    sa.Column('candidate_source_record_id', sa.UUID(), nullable=True),
    sa.Column('relationship_type', sa.String(length=64), nullable=True),
    sa.Column('match_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('date_evidence', sa.String(length=32), nullable=True),
    sa.Column('description_evidence', sa.String(length=32), nullable=True),
    sa.Column('amount_evidence', sa.String(length=32), nullable=True),
    sa.Column('payer_evidence', sa.String(length=32), nullable=True),
    sa.Column('participant_evidence', sa.String(length=32), nullable=True),
    sa.Column('evidence_for_match', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_against_match', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('suggested_allocated_amount', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('llm_provider', sa.String(length=64), nullable=True),
    sa.Column('llm_model', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_financial_event_id'], ['canonical_financial_events.id'], name=op.f('fk_splitwise_overlap_assessments_candidate_financial_event_id_canonical_financial_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['splitwise_expense_id'], ['splitwise_expenses.id'], name=op.f('fk_splitwise_overlap_assessments_splitwise_expense_id_splitwise_expenses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_splitwise_overlap_assessments'))
    )
    op.create_index(op.f('ix_splitwise_overlap_assessments_splitwise_expense_id'), 'splitwise_overlap_assessments', ['splitwise_expense_id'], unique=False)
    op.create_table('transaction_splits',
    sa.Column('canonical_financial_event_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('subcategory_id', sa.UUID(), nullable=True),
    sa.Column('household_member_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['canonical_financial_event_id'], ['canonical_financial_events.id'], name=op.f('fk_transaction_splits_canonical_financial_event_id_canonical_financial_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transaction_splits'))
    )
    op.create_index(op.f('ix_transaction_splits_canonical_financial_event_id'), 'transaction_splits', ['canonical_financial_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_splits_canonical_financial_event_id'), table_name='transaction_splits')
    op.drop_table('transaction_splits')
    op.drop_index(op.f('ix_splitwise_overlap_assessments_splitwise_expense_id'), table_name='splitwise_overlap_assessments')
    op.drop_table('splitwise_overlap_assessments')
    op.drop_index(op.f('ix_source_event_relationships_source_record_id'), table_name='source_event_relationships')
    op.drop_index(op.f('ix_source_event_relationships_canonical_financial_event_id'), table_name='source_event_relationships')
    op.drop_table('source_event_relationships')
    op.drop_index(op.f('ix_raw_source_rows_source_record_id'), table_name='raw_source_rows')
    op.drop_index(op.f('ix_raw_source_rows_row_fingerprint'), table_name='raw_source_rows')
    op.drop_index(op.f('ix_raw_source_rows_import_snapshot_id'), table_name='raw_source_rows')
    op.drop_table('raw_source_rows')
    op.drop_index(op.f('ix_import_jobs_status'), table_name='import_jobs')
    op.drop_index(op.f('ix_import_jobs_import_snapshot_id'), table_name='import_jobs')
    op.drop_index(op.f('ix_import_jobs_idempotency_key'), table_name='import_jobs')
    op.drop_table('import_jobs')
    op.drop_index(op.f('ix_import_interpretations_import_snapshot_id'), table_name='import_interpretations')
    op.drop_table('import_interpretations')
    op.drop_index(op.f('ix_financial_event_allocations_canonical_financial_event_id'), table_name='financial_event_allocations')
    op.drop_table('financial_event_allocations')
    op.drop_index(op.f('ix_categorization_assessments_canonical_financial_event_id'), table_name='categorization_assessments')
    op.drop_table('categorization_assessments')
    op.drop_index(op.f('ix_splitwise_participant_allocations_splitwise_expense_id'), table_name='splitwise_participant_allocations')
    op.drop_table('splitwise_participant_allocations')
    op.drop_index(op.f('ix_merchant_aliases_normalized_alias'), table_name='merchant_aliases')
    op.drop_index(op.f('ix_merchant_aliases_merchant_id'), table_name='merchant_aliases')
    op.drop_table('merchant_aliases')
    op.drop_index(op.f('ix_import_snapshots_uploaded_file_id'), table_name='import_snapshots')
    op.drop_index(op.f('ix_import_snapshots_import_status'), table_name='import_snapshots')
    op.drop_index(op.f('ix_import_snapshots_household_id'), table_name='import_snapshots')
    op.drop_table('import_snapshots')
    op.drop_index(op.f('ix_canonical_financial_events_overall_assessment_status'), table_name='canonical_financial_events')
    op.drop_index(op.f('ix_canonical_financial_events_household_id'), table_name='canonical_financial_events')
    op.drop_index(op.f('ix_canonical_financial_events_financial_account_id'), table_name='canonical_financial_events')
    op.drop_index(op.f('ix_canonical_financial_events_event_type'), table_name='canonical_financial_events')
    op.drop_index(op.f('ix_canonical_financial_events_event_date'), table_name='canonical_financial_events')
    op.drop_index(op.f('ix_canonical_financial_events_confirmed_subcategory_id'), table_name='canonical_financial_events')
    op.drop_index(op.f('ix_canonical_financial_events_confirmed_category_id'), table_name='canonical_financial_events')
    op.drop_index(op.f('ix_canonical_financial_events_analytics_inclusion_status'), table_name='canonical_financial_events')
    op.drop_table('canonical_financial_events')
    op.drop_index(op.f('ix_splitwise_expenses_source_record_id'), table_name='splitwise_expenses')
    op.drop_index(op.f('ix_splitwise_expenses_native_splitwise_expense_id'), table_name='splitwise_expenses')
    op.drop_index(op.f('ix_splitwise_expenses_expense_date'), table_name='splitwise_expenses')
    op.drop_table('splitwise_expenses')
    op.drop_index(op.f('ix_source_record_versions_source_record_id'), table_name='source_record_versions')
    op.drop_index(op.f('ix_source_record_versions_import_snapshot_id'), table_name='source_record_versions')
    op.drop_table('source_record_versions')
    op.drop_index(op.f('ix_merchants_household_id'), table_name='merchants')
    op.drop_index(op.f('ix_merchants_canonical_name'), table_name='merchants')
    op.drop_table('merchants')
    op.drop_index(op.f('ix_household_memberships_user_id'), table_name='household_memberships')
    op.drop_index(op.f('ix_household_memberships_household_member_id'), table_name='household_memberships')
    op.drop_index(op.f('ix_household_memberships_household_id'), table_name='household_memberships')
    op.drop_table('household_memberships')
    op.drop_index(op.f('ix_financial_accounts_household_id'), table_name='financial_accounts')
    op.drop_table('financial_accounts')
    op.drop_index(op.f('ix_debt_snapshots_debt_id'), table_name='debt_snapshots')
    op.drop_table('debt_snapshots')
    op.drop_index(op.f('ix_asset_snapshots_asset_id'), table_name='asset_snapshots')
    op.drop_table('asset_snapshots')
    op.drop_index(op.f('ix_uploaded_files_sha256_hash'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_import_status'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_household_id'), table_name='uploaded_files')
    op.drop_table('uploaded_files')
    op.drop_index(op.f('ix_source_records_source_type'), table_name='source_records')
    op.drop_index(op.f('ix_source_records_native_source_id'), table_name='source_records')
    op.drop_index(op.f('ix_source_records_household_id'), table_name='source_records')
    op.drop_index(op.f('ix_source_records_financial_account_id'), table_name='source_records')
    op.drop_index(op.f('ix_source_records_current_source_status'), table_name='source_records')
    op.drop_index(op.f('ix_source_records_content_fingerprint'), table_name='source_records')
    op.drop_index(op.f('ix_source_records_canonical_identity_fingerprint'), table_name='source_records')
    op.drop_table('source_records')
    op.drop_index(op.f('ix_recurring_cash_flow_items_household_id'), table_name='recurring_cash_flow_items')
    op.drop_table('recurring_cash_flow_items')
    op.drop_index(op.f('ix_planned_one_time_items_household_id'), table_name='planned_one_time_items')
    op.drop_table('planned_one_time_items')
    op.drop_index(op.f('ix_import_profiles_structural_signature'), table_name='import_profiles')
    op.drop_index(op.f('ix_import_profiles_household_id'), table_name='import_profiles')
    op.drop_table('import_profiles')
    op.drop_index(op.f('ix_household_members_user_account_id'), table_name='household_members')
    op.drop_index(op.f('ix_household_members_household_id'), table_name='household_members')
    op.drop_table('household_members')
    op.drop_index(op.f('ix_external_participants_household_id'), table_name='external_participants')
    op.drop_table('external_participants')
    op.drop_index(op.f('ix_debts_household_id'), table_name='debts')
    op.drop_table('debts')
    op.drop_index(op.f('ix_category_proposals_status'), table_name='category_proposals')
    op.drop_index(op.f('ix_category_proposals_household_id'), table_name='category_proposals')
    op.drop_table('category_proposals')
    op.drop_index(op.f('ix_categorization_rules_household_id'), table_name='categorization_rules')
    op.drop_table('categorization_rules')
    op.drop_index(op.f('ix_categories_parent_category_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_household_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_budgets_household_id'), table_name='budgets')
    op.drop_table('budgets')
    op.drop_index(op.f('ix_audit_events_user_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_timestamp'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_household_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_assets_household_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_user_accounts_email'), table_name='user_accounts')
    op.drop_table('user_accounts')
    op.drop_table('households')
    op.drop_table('financial_institutions')
    # ### end Alembic commands ###
